name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Git Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Grab Version'
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: 'Grab Changelog'
        run: |
          CHANGELOG=$(awk -v ver=$VERSION '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p' changelog.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: 'Publish Release'
        uses: 'actions/github-script@v6'
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.VERSION,
              name: process.env.VERSION,
              body: process.env.CHANGELOG,
              draft: false,
              prerelease: false
            })
